"""Licensing lifecycle enumerations.

Stored as VARCHAR guarded by named CHECK constraints, matching the convention
established in :mod:`app.domain.enums`. Open-ended business taxonomies
(document types, activity keys) stay plain TEXT so adding a value never needs a
migration; only closed workflow states get CHECK constraints.
"""

from __future__ import annotations

from enum import StrEnum


class EntityType(StrEnum):
    CORPORATION = "CORPORATION"
    LLC = "LLC"
    LP = "LP"
    LLP = "LLP"
    PARTNERSHIP = "PARTNERSHIP"
    SOLE_PROPRIETORSHIP = "SOLE_PROPRIETORSHIP"
    TRUST = "TRUST"
    OTHER = "OTHER"


class EntityStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DISSOLVED = "DISSOLVED"
    MERGED = "MERGED"
    PROSPECTIVE = "PROSPECTIVE"


class ActivityCategory(StrEnum):
    COLLECTION = "COLLECTION"
    SERVICING = "SERVICING"
    PURCHASING = "PURCHASING"
    COMMUNICATION = "COMMUNICATION"
    PAYMENT = "PAYMENT"
    LEGAL = "LEGAL"
    REPORTING = "REPORTING"
    SUPPORT = "SUPPORT"
    OTHER = "OTHER"


class ProfileStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class JurisdictionType(StrEnum):
    FEDERAL = "FEDERAL"
    STATE = "STATE"
    TERRITORY = "TERRITORY"
    COUNTY = "COUNTY"
    CITY = "CITY"
    OTHER_LOCAL = "OTHER_LOCAL"


class LicenseCategory(StrEnum):
    COLLECTION_AGENCY = "COLLECTION_AGENCY"
    DEBT_COLLECTION = "DEBT_COLLECTION"
    BUSINESS_LICENSE = "BUSINESS_LICENSE"
    CONSUMER_FINANCE = "CONSUMER_FINANCE"
    BRANCH = "BRANCH"
    REGISTRATION = "REGISTRATION"
    BOND = "BOND"
    ANNUAL_REPORT = "ANNUAL_REPORT"
    OTHER = "OTHER"


class LicenseStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    APPLICATION_IN_PROGRESS = "APPLICATION_IN_PROGRESS"
    PENDING_REGULATOR = "PENDING_REGULATOR"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    RENEWAL_IN_PROGRESS = "RENEWAL_IN_PROGRESS"
    EXPIRED = "EXPIRED"
    REINSTATING = "REINSTATING"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"
    SURRENDERED = "SURRENDERED"
    NOT_REQUIRED = "NOT_REQUIRED"
    UNKNOWN = "UNKNOWN"


#: Statuses that occupy the "one live authority" slot for an entity/jurisdiction
#: /license-type triple. Terminal and not-required states are excluded so a
#: surrendered licence never blocks a fresh application.
LIVE_LICENSE_STATUSES: tuple[str, ...] = (
    LicenseStatus.APPLICATION_IN_PROGRESS.value,
    LicenseStatus.PENDING_REGULATOR.value,
    LicenseStatus.APPROVED.value,
    LicenseStatus.ACTIVE.value,
    LicenseStatus.RENEWAL_IN_PROGRESS.value,
    LicenseStatus.REINSTATING.value,
    LicenseStatus.SUSPENDED.value,
)

TERMINAL_LICENSE_STATUSES: tuple[str, ...] = (
    LicenseStatus.REVOKED.value,
    LicenseStatus.SURRENDERED.value,
    LicenseStatus.NOT_REQUIRED.value,
)


class FilingChannel(StrEnum):
    """How a filing is transacted.

    Deliberately independent of *whether* a licence is required: an NMLS-managed
    licence can still carry supplemental requirements handled on paper, and a
    non-NMLS licence can be mandatory. See docs/license-inventory.md.
    """

    NMLS = "NMLS"
    STATE_PORTAL = "STATE_PORTAL"
    LOCAL_PORTAL = "LOCAL_PORTAL"
    PAPER = "PAPER"
    EMAIL = "EMAIL"
    VENDOR_MANAGED = "VENDOR_MANAGED"
    MULTIPLE_CHANNELS = "MULTIPLE_CHANNELS"
    UNKNOWN = "UNKNOWN"


class SourceConfidence(StrEnum):
    """How much we trust the provenance of an inventory row."""

    VERIFIED_DOCUMENT = "VERIFIED_DOCUMENT"
    REGULATOR_CONFIRMED = "REGULATOR_CONFIRMED"
    VENDOR_REPORTED = "VENDOR_REPORTED"
    TRACKER_IMPORT = "TRACKER_IMPORT"
    MANUAL_ENTRY = "MANUAL_ENTRY"
    UNVERIFIED = "UNVERIFIED"


class ObligationType(StrEnum):
    LICENSE_RENEWAL = "LICENSE_RENEWAL"
    BOND_RENEWAL = "BOND_RENEWAL"
    ANNUAL_REPORT = "ANNUAL_REPORT"
    FINANCIAL_DOCUMENT = "FINANCIAL_DOCUMENT"
    CERTIFICATE_RENEWAL = "CERTIFICATE_RENEWAL"
    INITIAL_APPLICATION = "INITIAL_APPLICATION"
    AMENDMENT = "AMENDMENT"
    DEFICIENCY_RESPONSE = "DEFICIENCY_RESPONSE"
    INFORMATION_RESPONSE = "INFORMATION_RESPONSE"
    SURRENDER = "SURRENDER"
    OTHER = "OTHER"


class ObligationStatus(StrEnum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    IN_CASE = "IN_CASE"
    SATISFIED = "SATISFIED"
    WAIVED = "WAIVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class CaseType(StrEnum):
    LICENSE_RENEWAL = "LICENSE_RENEWAL"
    INITIAL_LICENSE = "INITIAL_LICENSE"
    LICENSE_AMENDMENT = "LICENSE_AMENDMENT"
    BOND_RENEWAL = "BOND_RENEWAL"
    BOND_RIDER = "BOND_RIDER"
    ANNUAL_REPORT = "ANNUAL_REPORT"
    FINANCIAL_DOCUMENT = "FINANCIAL_DOCUMENT"
    DEFICIENCY_RESPONSE = "DEFICIENCY_RESPONSE"
    INFORMATION_RESPONSE = "INFORMATION_RESPONSE"
    SURRENDER = "SURRENDER"
    OTHER = "OTHER"


class CaseStage(StrEnum):
    """Operational stages mirroring the real renewal process."""

    DUE_IDENTIFIED = "DUE_IDENTIFIED"
    CASE_PLANNING = "CASE_PLANNING"
    VENDOR_OUTREACH_PENDING = "VENDOR_OUTREACH_PENDING"
    VENDOR_OUTREACH_SENT = "VENDOR_OUTREACH_SENT"
    VENDOR_QUESTIONS = "VENDOR_QUESTIONS"
    INTERNAL_INFORMATION_PENDING = "INTERNAL_INFORMATION_PENDING"
    ANSWERS_READY = "ANSWERS_READY"
    ANSWERS_SENT = "ANSWERS_SENT"
    DOCUMENT_CHECKLIST_RECEIVED = "DOCUMENT_CHECKLIST_RECEIVED"
    DOCUMENTS_PENDING = "DOCUMENTS_PENDING"
    PACKET_BUILDING = "PACKET_BUILDING"
    PACKET_READY_FOR_REVIEW = "PACKET_READY_FOR_REVIEW"
    PACKET_APPROVED = "PACKET_APPROVED"
    PACKET_SENT = "PACKET_SENT"
    FORM_RECEIVED = "FORM_RECEIVED"
    FORM_PREPARATION = "FORM_PREPARATION"
    FORM_MISSING_INFORMATION = "FORM_MISSING_INFORMATION"
    FORM_READY_FOR_REVIEW = "FORM_READY_FOR_REVIEW"
    SIGNATURE_PENDING = "SIGNATURE_PENDING"
    SIGNED_FORM_RECEIVED = "SIGNED_FORM_RECEIVED"
    SUBMISSION_PENDING = "SUBMISSION_PENDING"
    SUBMITTED_TO_VENDOR = "SUBMITTED_TO_VENDOR"
    SUBMITTED_TO_REGULATOR = "SUBMITTED_TO_REGULATOR"
    VENDOR_VALIDATION = "VENDOR_VALIDATION"
    REGULATOR_REVIEW = "REGULATOR_REVIEW"
    DEFICIENCY_RECEIVED = "DEFICIENCY_RECEIVED"
    RENEWED_EVIDENCE_RECEIVED = "RENEWED_EVIDENCE_RECEIVED"
    INVENTORY_UPDATE_PENDING = "INVENTORY_UPDATE_PENDING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_INTERNAL = "WAITING_INTERNAL"
    WAITING_VENDOR = "WAITING_VENDOR"
    WAITING_SIGNATURE = "WAITING_SIGNATURE"
    WAITING_SUBMISSION = "WAITING_SUBMISSION"
    WAITING_REGULATOR = "WAITING_REGULATOR"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    OVERDUE = "OVERDUE"


class CasePriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CaseInformationRequestStatus(StrEnum):
    OPEN = "OPEN"
    REQUESTED = "REQUESTED"
    ANSWER_PROPOSED = "ANSWER_PROPOSED"
    ANSWER_REVIEW = "ANSWER_REVIEW"
    ANSWER_APPROVED = "ANSWER_APPROVED"
    PROVIDED_TO_VENDOR = "PROVIDED_TO_VENDOR"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    CANCELLED = "CANCELLED"


class OrganizationRole(StrEnum):
    """Configurable partner roles. No vendor names are hard-coded anywhere."""

    LICENSING_VENDOR = "LICENSING_VENDOR"
    BOND_PROVIDER = "BOND_PROVIDER"
    NMLS = "NMLS"
    STATE_REGULATOR = "STATE_REGULATOR"
    LOCAL_REGULATOR = "LOCAL_REGULATOR"
    INTERNAL_INFORMATION_OWNER = "INTERNAL_INFORMATION_OWNER"
    AUTHORIZED_SIGNATORY = "AUTHORIZED_SIGNATORY"
    FINAL_SUBMITTER = "FINAL_SUBMITTER"
    LICENSING_OPERATOR = "LICENSING_OPERATOR"
    COMPLIANCE_REVIEWER = "COMPLIANCE_REVIEWER"


class BondStatus(StrEnum):
    """Bond lifecycle, including NMLS Electronic Surety Bond tracking."""

    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    CONTINUED = "CONTINUED"
    RIDER_PENDING = "RIDER_PENDING"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class BondChannel(StrEnum):
    """Bond processing route. NMLS ESB is distinct from paper and vendor flows."""

    NMLS_ESB = "NMLS_ESB"
    PAPER_ORIGINAL = "PAPER_ORIGINAL"
    VENDOR_MANAGED = "VENDOR_MANAGED"
    STATE_SPECIFIC = "STATE_SPECIFIC"
    UNKNOWN = "UNKNOWN"


class LicenseEventSourceType(StrEnum):
    REGULATOR_DOCUMENT = "REGULATOR_DOCUMENT"
    VENDOR_NOTICE = "VENDOR_NOTICE"
    EMAIL_EVIDENCE = "EMAIL_EVIDENCE"
    TRACKER_IMPORT = "TRACKER_IMPORT"
    MANUAL_UPDATE = "MANUAL_UPDATE"
    CASE_COMPLETION = "CASE_COMPLETION"
    SYSTEM_LIFECYCLE = "SYSTEM_LIFECYCLE"


class CaseEmailLinkStatus(StrEnum):
    """Lifecycle of a proposed correspondence link.

    A link is only evidence once a human has confirmed it. Everything the
    portal presents as a case's correspondence is drawn from CONFIRMED links,
    so a wrong automatic match is visible and reversible, never silent.
    """

    PROPOSED = "PROPOSED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
