"""Closed workflow taxonomies for controlled communications."""

from enum import StrEnum


class ResponseType(StrEnum):
    ACKNOWLEDGEMENT = "ACKNOWLEDGEMENT"
    INFORMATION_RESPONSE = "INFORMATION_RESPONSE"
    DOCUMENT_RESPONSE = "DOCUMENT_RESPONSE"
    CLARIFICATION_RESPONSE = "CLARIFICATION_RESPONSE"
    PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION"
    FILING_CONFIRMATION = "FILING_CONFIRMATION"
    REGULATOR_RESPONSE = "REGULATOR_RESPONSE"
    BOND_RESPONSE = "BOND_RESPONSE"
    INTERNAL_FORWARD = "INTERNAL_FORWARD"
    NO_RESPONSE_REQUIRED = "NO_RESPONSE_REQUIRED"


class RecipientMode(StrEnum):
    REPLY = "REPLY"
    REPLY_ALL = "REPLY_ALL"
    MANUAL = "MANUAL"
    INTERNAL_FORWARD = "INTERNAL_FORWARD"
    NONE = "NONE"


class ReadinessStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    NOT_READY = "NOT_READY"
    READY_FOR_DRAFT = "READY_FOR_DRAFT"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    READY_TO_SEND = "READY_TO_SEND"
    BLOCKED = "BLOCKED"


class CommunicationDraftStatus(StrEnum):
    LOCAL_DRAFT = "LOCAL_DRAFT"
    GRAPH_DRAFT_PENDING = "GRAPH_DRAFT_PENDING"
    GRAPH_DRAFT_CREATED = "GRAPH_DRAFT_CREATED"
    REVIEW_IN_PROGRESS = "REVIEW_IN_PROGRESS"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    PENDING_SEND_APPROVAL = "PENDING_SEND_APPROVAL"
    APPROVED_TO_SEND = "APPROVED_TO_SEND"
    SEND_QUEUED = "SEND_QUEUED"
    SENDING = "SENDING"
    SEND_ACCEPTED = "SEND_ACCEPTED"
    SEND_AMBIGUOUS = "SEND_AMBIGUOUS"
    SENT_COPY_VERIFIED = "SENT_COPY_VERIFIED"
    SEND_FAILED_RETRYABLE = "SEND_FAILED_RETRYABLE"
    SEND_FAILED_REVIEW = "SEND_FAILED_REVIEW"
    CANCELLED = "CANCELLED"


class ApprovalDecision(StrEnum):
    PENDING_SECOND_APPROVAL = "PENDING_SECOND_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    INVALIDATED = "INVALIDATED"


class SendAttemptStatus(StrEnum):
    STARTED = "STARTED"
    ACCEPTED = "ACCEPTED"
    AMBIGUOUS = "AMBIGUOUS"
    SENT_COPY_VERIFIED = "SENT_COPY_VERIFIED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    CANCELLED = "CANCELLED"


class MoveAttemptStatus(StrEnum):
    STARTED = "STARTED"
    MOVED = "MOVED"
    VERIFIED = "VERIFIED"
    AMBIGUOUS = "AMBIGUOUS"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"


class DeliveryStatus(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"
    NO_NDR_OBSERVED = "NO_NDR_OBSERVED"
    NDR_RECEIVED = "NDR_RECEIVED"
    DELIVERY_CONFIRMED = "DELIVERY_CONFIRMED"


class CommunicationJobType(StrEnum):
    CREATE_GRAPH_DRAFT = "CREATE_GRAPH_DRAFT"
    SYNC_GRAPH_DRAFT = "SYNC_GRAPH_DRAFT"
    UPLOAD_DRAFT_ATTACHMENTS = "UPLOAD_DRAFT_ATTACHMENTS"
    SEND_DRAFT = "SEND_DRAFT"
    RECONCILE_SEND = "RECONCILE_SEND"
    MOVE_SOURCE_MESSAGE = "MOVE_SOURCE_MESSAGE"
    VERIFY_SOURCE_MOVE = "VERIFY_SOURCE_MOVE"
    COMPLETE_EMAIL_WORKFLOW = "COMPLETE_EMAIL_WORKFLOW"
    RECONCILE_GRAPH_DRAFT = "RECONCILE_GRAPH_DRAFT"


class CommunicationJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    CANCELLED = "CANCELLED"


class TemplateVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"


class DraftAttachmentStatus(StrEnum):
    SELECTED = "SELECTED"
    VALIDATED = "VALIDATED"
    GRAPH_UPLOAD_PENDING = "GRAPH_UPLOAD_PENDING"
    GRAPH_UPLOADED = "GRAPH_UPLOADED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    REMOVED = "REMOVED"


class WorkflowCompletionType(StrEnum):
    RESPONSE_SENT_AND_ROUTED = "RESPONSE_SENT_AND_ROUTED"
    NO_RESPONSE_REQUIRED_AND_ROUTED = "NO_RESPONSE_REQUIRED_AND_ROUTED"
    ACKNOWLEDGEMENT_SENT_AND_ROUTED = "ACKNOWLEDGEMENT_SENT_AND_ROUTED"
    MANUAL_COMMUNICATION_CONFIRMED_AND_ROUTED = "MANUAL_COMMUNICATION_CONFIRMED_AND_ROUTED"
