"""Canonical jurisdiction, license, route, and type taxonomy."""

US_STATES = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DC": "District of Columbia",
}

LICENSE_PHRASES = {
    "collection agency license": "Collection Agency License",
    "debt collector license": "Debt Collector License",
    "money transmitter license": "Money Transmitter License",
    "business license": "Business License",
}

DESTINATIONS = {
    "missing_information_request": "08_Info_Required",
    "bond_correspondence": "03_Cornerstone_Bonds",
    "invoice_or_fee": "06_Invoices",
    "submission_confirmation": "07_Proof_Received",
    "license_or_proof_received": "07_Proof_Received",
    "regulator_correspondence": "05_Regulators",
    "internal_followup": "09_Internal_Followups",
}

VALID_DESTINATIONS = sorted(set(DESTINATIONS.values()) | {"02_RASI", "04_NMLS"})
