"""Extensible string taxonomies for the document repository.

Values are stored as TEXT with CHECK constraints only for closed workflow
states. DocumentType intentionally remains plain TEXT in PostgreSQL so adding
a business type does not require a database-native enum migration.
"""

from enum import StrEnum


class DocumentType(StrEnum):
    ARTICLES_OF_INCORPORATION = "ARTICLES_OF_INCORPORATION"
    CERTIFICATE_OF_GOOD_STANDING = "CERTIFICATE_OF_GOOD_STANDING"
    FOREIGN_QUALIFICATION = "FOREIGN_QUALIFICATION"
    REGISTERED_AGENT_DOCUMENT = "REGISTERED_AGENT_DOCUMENT"
    COLLECTION_AGENCY_LICENSE = "COLLECTION_AGENCY_LICENSE"
    DEBT_COLLECTION_LICENSE = "DEBT_COLLECTION_LICENSE"
    BUSINESS_LICENSE = "BUSINESS_LICENSE"
    NMLS_RECORD = "NMLS_RECORD"
    SURETY_BOND = "SURETY_BOND"
    BOND_RIDER = "BOND_RIDER"
    BOND_CONTINUATION = "BOND_CONTINUATION"
    ANNUAL_REPORT = "ANNUAL_REPORT"
    RENEWAL_APPLICATION = "RENEWAL_APPLICATION"
    INITIAL_APPLICATION = "INITIAL_APPLICATION"
    REGULATOR_NOTICE = "REGULATOR_NOTICE"
    DEFICIENCY_NOTICE = "DEFICIENCY_NOTICE"
    INFORMATION_REQUEST = "INFORMATION_REQUEST"
    INFORMATION_RESPONSE = "INFORMATION_RESPONSE"
    INVOICE = "INVOICE"
    PAYMENT_RECEIPT = "PAYMENT_RECEIPT"
    SUBMISSION_RECEIPT = "SUBMISSION_RECEIPT"
    PROOF_OF_SUBMISSION = "PROOF_OF_SUBMISSION"
    ISSUED_LICENSE = "ISSUED_LICENSE"
    LICENSE_CERTIFICATE = "LICENSE_CERTIFICATE"
    OFFICIAL_FORM = "OFFICIAL_FORM"
    STATE_CHECKLIST = "STATE_CHECKLIST"
    BACKGROUND_CHECK = "BACKGROUND_CHECK"
    FINGERPRINT_RECORD = "FINGERPRINT_RECORD"
    FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT"
    OWNERSHIP_DISCLOSURE = "OWNERSHIP_DISCLOSURE"
    OFFICER_INFORMATION = "OFFICER_INFORMATION"
    CALL_RECORDING_POLICY = "CALL_RECORDING_POLICY"
    PRIVACY_POLICY = "PRIVACY_POLICY"
    COMPLAINT_POLICY = "COMPLAINT_POLICY"
    INTERNAL_APPROVAL = "INTERNAL_APPROVAL"
    OTHER = "OTHER"


class DrivePurpose(StrEnum):
    MASTER_DOCUMENTS = "MASTER_DOCUMENTS"
    WORKING_DOCUMENTS = "WORKING_DOCUMENTS"
    BONDS = "BONDS"
    SUBMITTED_FILINGS = "SUBMITTED_FILINGS"
    LICENSES_CERTIFICATES = "LICENSES_CERTIFICATES"
    REGULATOR_CORRESPONDENCE = "REGULATOR_CORRESPONDENCE"
    PAYMENTS_RECEIPTS = "PAYMENTS_RECEIPTS"
    OFFICIAL_FORMS_CHECKLISTS = "OFFICIAL_FORMS_CHECKLISTS"
    QUARANTINE = "QUARANTINE"


class LifecycleStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"
    QUARANTINED = "QUARANTINED"
    MISSING = "MISSING"
    DELETED_EXTERNALLY = "DELETED_EXTERNALLY"


class ApprovalStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ConfidentialityLevel(StrEnum):
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class SourceType(StrEnum):
    EMAIL_ATTACHMENT = "EMAIL_ATTACHMENT"
    MANUAL_UPLOAD = "MANUAL_UPLOAD"
    GENERATED_PACKET = "GENERATED_PACKET"
    SHAREPOINT_EXISTING = "SHAREPOINT_EXISTING"
    PROTOTYPE_IMPORT = "PROTOTYPE_IMPORT"


class StorageStatus(StrEnum):
    UPLOADING = "UPLOADING"
    AVAILABLE = "AVAILABLE"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"
    MISSING = "MISSING"
    DELETED_EXTERNALLY = "DELETED_EXTERNALLY"


class LinkType(StrEnum):
    EMAIL = "EMAIL"
    EMAIL_ATTACHMENT = "EMAIL_ATTACHMENT"
    TASK = "TASK"
    CLASSIFICATION = "CLASSIFICATION"
    LICENSE = "LICENSE"
    BOND = "BOND"
    JURISDICTION = "JURISDICTION"
    VENDOR = "VENDOR"
    FILING = "FILING"
    PAYMENT = "PAYMENT"
    PACKET = "PACKET"


class DocumentJobType(StrEnum):
    VERIFY_SITE_ACCESS = "VERIFY_SITE_ACCESS"
    BOOTSTRAP_REPOSITORY = "BOOTSTRAP_REPOSITORY"
    UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT"
    PROMOTE_ATTACHMENT = "PROMOTE_ATTACHMENT"
    SYNC_DOCUMENT_METADATA = "SYNC_DOCUMENT_METADATA"
    RECONCILE_DRIVE = "RECONCILE_DRIVE"
    VERIFY_DOCUMENT_HASH = "VERIFY_DOCUMENT_HASH"
    MIGRATE_EVIDENCE = "MIGRATE_EVIDENCE"
    MARK_EXPIRED_DOCUMENTS = "MARK_EXPIRED_DOCUMENTS"


class DocumentJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    CANCELLED = "CANCELLED"
