"""Import-pipeline enumerations."""

from __future__ import annotations

from enum import StrEnum


class ImportRunStatus(StrEnum):
    PENDING = "PENDING"
    PLANNING = "PLANNING"
    PLANNED = "PLANNED"
    APPLYING = "APPLYING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ImportRowAction(StrEnum):
    INSERT = "INSERT"
    UPDATE = "UPDATE"
    SKIP_UNCHANGED = "SKIP_UNCHANGED"
    SKIP_DUPLICATE = "SKIP_DUPLICATE"
    SKIP_NEWER_TARGET = "SKIP_NEWER_TARGET"
    CONFLICT_REVIEW = "CONFLICT_REVIEW"
    ERROR = "ERROR"


#: Actions that mutate inventory. Everything else is reported but not applied.
APPLYING_ROW_ACTIONS: tuple[str, ...] = (
    ImportRowAction.INSERT.value,
    ImportRowAction.UPDATE.value,
)


class ImportErrorCode(StrEnum):
    MISSING_REQUIRED_COLUMN = "MISSING_REQUIRED_COLUMN"
    UNRESOLVED_LEGAL_ENTITY = "UNRESOLVED_LEGAL_ENTITY"
    UNRESOLVED_JURISDICTION = "UNRESOLVED_JURISDICTION"
    UNRESOLVED_LICENSE_TYPE = "UNRESOLVED_LICENSE_TYPE"
    INVALID_DATE = "INVALID_DATE"
    INVALID_STATUS = "INVALID_STATUS"
    INVALID_FILING_CHANNEL = "INVALID_FILING_CHANNEL"
    INVALID_DATE_SEQUENCE = "INVALID_DATE_SEQUENCE"
    DUPLICATE_ROW_IN_FILE = "DUPLICATE_ROW_IN_FILE"
    CONFLICTING_EXISTING_RECORD = "CONFLICTING_EXISTING_RECORD"
    TARGET_MODIFIED_MORE_RECENTLY = "TARGET_MODIFIED_MORE_RECENTLY"
    INVALID_BOND_DETAILS = "INVALID_BOND_DETAILS"
    ROW_PERSIST_FAILED = "ROW_PERSIST_FAILED"


class SpreadsheetFormat(StrEnum):
    XLSX = "XLSX"
    CSV = "CSV"


#: Extensions rejected outright. Macro-enabled workbooks are never parsed.
REJECTED_EXTENSIONS: frozenset[str] = frozenset({".xlsm", ".xltm", ".xlsb", ".xls"})


class TrackerColumn(StrEnum):
    """Canonical destination fields an Admin maps source columns onto."""

    LEGAL_ENTITY = "LEGAL_ENTITY"
    JURISDICTION = "JURISDICTION"
    LICENSE_TYPE = "LICENSE_TYPE"
    LICENSE_NUMBER = "LICENSE_NUMBER"
    NMLS_LICENSE_ID = "NMLS_LICENSE_ID"
    STATUS = "STATUS"
    FILING_CHANNEL = "FILING_CHANNEL"
    ISSUE_DATE = "ISSUE_DATE"
    EFFECTIVE_DATE = "EFFECTIVE_DATE"
    EXPIRATION_DATE = "EXPIRATION_DATE"
    RENEWAL_DUE_DATE = "RENEWAL_DUE_DATE"
    VENDOR = "VENDOR"
    REGULATOR = "REGULATOR"
    BOND_PROVIDER = "BOND_PROVIDER"
    BOND_NUMBER = "BOND_NUMBER"
    BOND_AMOUNT = "BOND_AMOUNT"
    BOND_EFFECTIVE_DATE = "BOND_EFFECTIVE_DATE"
    BOND_EXPIRATION_DATE = "BOND_EXPIRATION_DATE"
    ANNUAL_REPORT_DATE = "ANNUAL_REPORT_DATE"
    RESPONSIBLE_OWNER = "RESPONSIBLE_OWNER"
    NOTES = "NOTES"
    NEXT_ACTION = "NEXT_ACTION"
    SOURCE_DOCUMENT_REFERENCE = "SOURCE_DOCUMENT_REFERENCE"


#: Minimum mapping required before a run may be applied.
REQUIRED_TRACKER_COLUMNS: tuple[str, ...] = (
    TrackerColumn.LEGAL_ENTITY.value,
    TrackerColumn.JURISDICTION.value,
    TrackerColumn.LICENSE_TYPE.value,
)
