"""ORM models. Importing this package registers every table on Base.metadata."""

from app.db.base import Base
from app.models.classification import Classification
from app.models.communication import (
    CommunicationJob,
    MessageMoveAttempt,
    OutboundSendAttempt,
    RecipientPolicyRule,
    ResponsePlan,
    ResponseTemplate,
    ResponseTemplateVersion,
    SendApproval,
    WorkflowCompletionRecord,
)
from app.models.deadlines import ComplianceDeadline, DeadlineEvent, DeadlineRule
from app.models.document import (
    Document,
    DocumentJob,
    DocumentLink,
    DocumentMetadataEvent,
    DocumentVersion,
)
from app.models.draft import OutboundDraft, OutboundDraftAttachment, OutboundDraftVersion
from app.models.email import Email, EmailAttachment, EmailRecipient
from app.models.event import AuditEvent, EmailProcessingEvent
from app.models.forms import (
    FormFieldMapping,
    FormFieldValue,
    FormInstance,
    FormTemplate,
    FormTemplateField,
)
from app.models.graph_subscription import GraphSubscription
from app.models.heartbeat import WorkerHeartbeat
from app.models.information import (
    InformationDefinition,
    InformationOwnerAssignment,
    InformationValue,
    InformationValueUsage,
)
from app.models.job import GraphJob
from app.models.licensing import (
    BusinessActivity,
    CaseInformationRequest,
    ComplianceCase,
    ComplianceCaseStageEvent,
    ComplianceObligation,
    Jurisdiction,
    LegalEntity,
    LicenseBond,
    LicenseInventory,
    LicenseStatusEvent,
    LicenseType,
    LicensingJob,
    LicensingNotification,
    OperatingProfile,
)
from app.models.mailbox import Mailbox, MailboxFolder, MailboxSyncState
from app.models.milestone4 import (
    ClassificationFieldCorrection,
    ClassificationRule,
    ClassificationRuleSet,
    ClassificationRun,
    Organization,
    OrganizationAddress,
    OrganizationDomain,
    PromptVersion,
    UserPreference,
    UserPrincipal,
    UserRoleSnapshot,
)
from app.models.notification import GraphNotificationReceipt
from app.models.outbox import OutboxEvent
from app.models.packets import (
    DocumentPacket,
    DocumentPacketItem,
    PacketTemplate,
    PacketTemplateItem,
)
from app.models.requirements import (
    AssessmentOverride,
    RequirementAssessment,
    RequirementAssessmentResult,
    RequirementRule,
    RequirementRuleSet,
    RequirementRuleSource,
    RequirementSource,
    RequirementSourceSnapshot,
)
from app.models.review import ClassificationReview
from app.models.sharepoint import (
    SharePointDrive,
    SharePointFolder,
    SharePointSite,
    SharePointSyncState,
    SharePointUploadSession,
)
from app.models.task import LicensingTask, TaskComment, TaskEvent, TaskRequestedItem
from app.models.tracker import TrackerImportRow, TrackerImportRun

__all__ = [
    "AssessmentOverride",
    "AuditEvent",
    "Base",
    "BusinessActivity",
    "CaseInformationRequest",
    "Classification",
    "ClassificationFieldCorrection",
    "ClassificationReview",
    "ClassificationRule",
    "ClassificationRuleSet",
    "ClassificationRun",
    "CommunicationJob",
    "ComplianceCase",
    "ComplianceCaseStageEvent",
    "ComplianceDeadline",
    "ComplianceObligation",
    "DeadlineEvent",
    "DeadlineRule",
    "Document",
    "DocumentJob",
    "DocumentLink",
    "DocumentMetadataEvent",
    "DocumentPacket",
    "DocumentPacketItem",
    "DocumentVersion",
    "Email",
    "EmailAttachment",
    "EmailProcessingEvent",
    "EmailRecipient",
    "FormFieldMapping",
    "FormFieldValue",
    "FormInstance",
    "FormTemplate",
    "FormTemplateField",
    "GraphJob",
    "GraphNotificationReceipt",
    "GraphSubscription",
    "InformationDefinition",
    "InformationOwnerAssignment",
    "InformationValue",
    "InformationValueUsage",
    "Jurisdiction",
    "LegalEntity",
    "LicenseBond",
    "LicenseInventory",
    "LicenseStatusEvent",
    "LicenseType",
    "LicensingJob",
    "LicensingNotification",
    "LicensingTask",
    "Mailbox",
    "MailboxFolder",
    "MailboxSyncState",
    "MessageMoveAttempt",
    "OperatingProfile",
    "Organization",
    "OrganizationAddress",
    "OrganizationDomain",
    "OutboundDraft",
    "OutboundDraftAttachment",
    "OutboundDraftVersion",
    "OutboundSendAttempt",
    "OutboxEvent",
    "PacketTemplate",
    "PacketTemplateItem",
    "PromptVersion",
    "RecipientPolicyRule",
    "RequirementAssessment",
    "RequirementAssessmentResult",
    "RequirementRule",
    "RequirementRuleSet",
    "RequirementRuleSource",
    "RequirementSource",
    "RequirementSourceSnapshot",
    "ResponsePlan",
    "ResponseTemplate",
    "ResponseTemplateVersion",
    "SendApproval",
    "SharePointDrive",
    "SharePointFolder",
    "SharePointSite",
    "SharePointSyncState",
    "SharePointUploadSession",
    "TaskComment",
    "TaskEvent",
    "TaskRequestedItem",
    "TrackerImportRow",
    "TrackerImportRun",
    "UserPreference",
    "UserPrincipal",
    "UserRoleSnapshot",
    "WorkerHeartbeat",
    "WorkflowCompletionRecord",
]
