"""Closed vocabularies for governed portal assistance."""

from enum import StrEnum


class PortalType(StrEnum):
    NMLS = "NMLS"
    STATE_REGULATOR = "STATE_REGULATOR"
    LOCAL_REGULATOR = "LOCAL_REGULATOR"
    SECRETARY_OF_STATE = "SECRETARY_OF_STATE"
    BOND_PROVIDER = "BOND_PROVIDER"
    LICENSING_VENDOR = "LICENSING_VENDOR"
    PAYMENT = "PAYMENT"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    OTHER = "OTHER"


class AutomationLevel(StrEnum):
    PREPARE_ONLY = "PREPARE_ONLY"
    NAVIGATION_ASSIST = "NAVIGATION_ASSIST"
    ASSISTED_ENTRY = "ASSISTED_ENTRY"
    UPLOAD_ASSIST = "UPLOAD_ASSIST"
    PRE_SUBMISSION_ASSIST = "PRE_SUBMISSION_ASSIST"
    API_ASSISTED = "API_ASSISTED"


AUTOMATION_LEVEL_RANK = {
    AutomationLevel.PREPARE_ONLY.value: 0,
    AutomationLevel.NAVIGATION_ASSIST.value: 1,
    AutomationLevel.ASSISTED_ENTRY.value: 2,
    AutomationLevel.UPLOAD_ASSIST.value: 3,
    AutomationLevel.PRE_SUBMISSION_ASSIST.value: 4,
    AutomationLevel.API_ASSISTED.value: 5,
}


class PortalApprovalStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    REVIEW_PENDING = "REVIEW_PENDING"
    APPROVED_PREPARE_ONLY = "APPROVED_PREPARE_ONLY"
    APPROVED_ASSISTED = "APPROVED_ASSISTED"
    APPROVED_API = "APPROVED_API"
    AUTOMATION_PROHIBITED = "AUTOMATION_PROHIBITED"
    TEMPORARILY_SUSPENDED = "TEMPORARILY_SUSPENDED"
    EXPIRED = "EXPIRED"
    RETIRED = "RETIRED"


APPROVED_PORTAL_STATUSES = frozenset(
    {
        PortalApprovalStatus.APPROVED_PREPARE_ONLY.value,
        PortalApprovalStatus.APPROVED_ASSISTED.value,
        PortalApprovalStatus.APPROVED_API.value,
    }
)


class PortalReviewStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"


class CredentialModel(StrEnum):
    INDIVIDUAL_USER_LOGIN = "INDIVIDUAL_USER_LOGIN"
    ORGANIZATION_USER_LOGIN = "ORGANIZATION_USER_LOGIN"
    APPROVED_SERVICE_ACCOUNT = "APPROVED_SERVICE_ACCOUNT"
    OAUTH_DELEGATED = "OAUTH_DELEGATED"
    OAUTH_APPLICATION = "OAUTH_APPLICATION"
    API_KEY = "API_KEY"
    CERTIFICATE = "CERTIFICATE"
    NO_LOGIN = "NO_LOGIN"
    UNKNOWN = "UNKNOWN"


class AuthorizationStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class AdapterStatus(StrEnum):
    DRAFT = "DRAFT"
    TESTING = "TESTING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    RETIRED = "RETIRED"


class PortalFieldSourceType(StrEnum):
    FORM_INSTANCE_FIELD = "FORM_INSTANCE_FIELD"
    INFORMATION_REGISTRY = "INFORMATION_REGISTRY"
    LEGAL_ENTITY = "LEGAL_ENTITY"
    LICENSE_INVENTORY = "LICENSE_INVENTORY"
    COMPLIANCE_CASE = "COMPLIANCE_CASE"
    DOCUMENT_METADATA = "DOCUMENT_METADATA"
    MANUAL_OPERATOR_INPUT = "MANUAL_OPERATOR_INPUT"
    CALCULATED = "CALCULATED"
    ATTESTATION = "ATTESTATION"
    SIGNATURE = "SIGNATURE"
    PAYMENT = "PAYMENT"


class PortalRunStatus(StrEnum):
    PLANNED = "PLANNED"
    READY = "READY"
    WAITING_OPERATOR = "WAITING_OPERATOR"
    SESSION_ACTIVE = "SESSION_ACTIVE"
    WAITING_LOGIN = "WAITING_LOGIN"
    WAITING_TERMS_ACCEPTANCE = "WAITING_TERMS_ACCEPTANCE"
    WAITING_MFA = "WAITING_MFA"
    WAITING_CAPTCHA = "WAITING_CAPTCHA"
    ENTRY_IN_PROGRESS = "ENTRY_IN_PROGRESS"
    UPLOAD_IN_PROGRESS = "UPLOAD_IN_PROGRESS"
    VALIDATION_REQUIRED = "VALIDATION_REQUIRED"
    DISCREPANCIES_FOUND = "DISCREPANCIES_FOUND"
    READY_FOR_PRE_SUBMISSION_REVIEW = "READY_FOR_PRE_SUBMISSION_REVIEW"
    PRE_SUBMISSION_APPROVED = "PRE_SUBMISSION_APPROVED"
    WAITING_ATTESTATION = "WAITING_ATTESTATION"
    WAITING_SIGNATURE = "WAITING_SIGNATURE"
    WAITING_PAYMENT = "WAITING_PAYMENT"
    WAITING_FINAL_SUBMIT = "WAITING_FINAL_SUBMIT"
    SUBMISSION_RESULT_PENDING = "SUBMISSION_RESULT_PENDING"
    SUBMITTED = "SUBMITTED"
    SUBMISSION_FAILED = "SUBMISSION_FAILED"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    FAILED_REVIEW = "FAILED_REVIEW"


class BrowserSessionStatus(StrEnum):
    REQUESTED = "REQUESTED"
    STARTING = "STARTING"
    ACTIVE_AUTOMATION = "ACTIVE_AUTOMATION"
    ACTIVE_HUMAN_CONTROL = "ACTIVE_HUMAN_CONTROL"
    PAUSED = "PAUSED"
    EXPIRED = "EXPIRED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


ACTIVE_BROWSER_SESSION_STATUSES = frozenset(
    {
        BrowserSessionStatus.REQUESTED.value,
        BrowserSessionStatus.STARTING.value,
        BrowserSessionStatus.ACTIVE_AUTOMATION.value,
        BrowserSessionStatus.ACTIVE_HUMAN_CONTROL.value,
        BrowserSessionStatus.PAUSED.value,
    }
)


class PortalStepType(StrEnum):
    NAVIGATE = "NAVIGATE"
    LOGIN_HANDOFF = "LOGIN_HANDOFF"
    TERMS_HANDOFF = "TERMS_HANDOFF"
    MFA_HANDOFF = "MFA_HANDOFF"
    CAPTCHA_HANDOFF = "CAPTCHA_HANDOFF"
    FIELD_ENTRY = "FIELD_ENTRY"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    VALIDATION = "VALIDATION"
    PRE_SUBMISSION_CAPTURE = "PRE_SUBMISSION_CAPTURE"
    ATTESTATION_HANDOFF = "ATTESTATION_HANDOFF"
    SIGNATURE_HANDOFF = "SIGNATURE_HANDOFF"
    PAYMENT_HANDOFF = "PAYMENT_HANDOFF"
    FINAL_SUBMIT_HANDOFF = "FINAL_SUBMIT_HANDOFF"
    SUBMISSION_RESULT_CAPTURE = "SUBMISSION_RESULT_CAPTURE"


class PortalStepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_HUMAN = "WAITING_HUMAN"
    COMPLETED = "COMPLETED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    CANCELLED = "CANCELLED"


class PortalFieldStatus(StrEnum):
    PENDING = "PENDING"
    AUTO_ENTERED = "AUTO_ENTERED"
    HUMAN_ENTERED = "HUMAN_ENTERED"
    HUMAN_ONLY = "HUMAN_ONLY"
    VERIFIED = "VERIFIED"
    DISCREPANCY = "DISCREPANCY"
    REJECTED = "REJECTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    BLOCKED = "BLOCKED"


class PortalDocumentStatus(StrEnum):
    SELECTED = "SELECTED"
    VALIDATED = "VALIDATED"
    UPLOAD_PENDING = "UPLOAD_PENDING"
    UPLOADING = "UPLOADING"
    UPLOADED = "UPLOADED"
    VERIFIED = "VERIFIED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    REMOVED = "REMOVED"


class HandoffType(StrEnum):
    LOGIN = "LOGIN"
    TERMS_ACCEPTANCE = "TERMS_ACCEPTANCE"
    MFA = "MFA"
    CAPTCHA = "CAPTCHA"
    SENSITIVE_FIELD = "SENSITIVE_FIELD"
    ATTESTATION = "ATTESTATION"
    SIGNATURE = "SIGNATURE"
    PAYMENT = "PAYMENT"
    FINAL_SUBMIT = "FINAL_SUBMIT"
    UNEXPECTED_PAGE = "UNEXPECTED_PAGE"
    PORTAL_ERROR = "PORTAL_ERROR"


class HandoffStatus(StrEnum):
    REQUESTED = "REQUESTED"
    ACCEPTED = "ACCEPTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"


class SnapshotStatus(StrEnum):
    DRAFT = "DRAFT"
    DISCREPANCIES_FOUND = "DISCREPANCIES_FOUND"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class AttestationStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    WAITING = "WAITING"
    COMPLETED_BY_HUMAN = "COMPLETED_BY_HUMAN"
    DECLINED = "DECLINED"
    FAILED = "FAILED"


class PaymentStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    ESTIMATED = "ESTIMATED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    WAITING_HUMAN_PAYMENT = "WAITING_HUMAN_PAYMENT"
    PAID_EXTERNALLY = "PAID_EXTERNALLY"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SubmissionEvidenceType(StrEnum):
    PORTAL_CONFIRMATION = "PORTAL_CONFIRMATION"
    RECEIPT = "RECEIPT"
    PAYMENT_RECEIPT = "PAYMENT_RECEIPT"
    SUBMISSION_PDF = "SUBMISSION_PDF"
    SCREENSHOT = "SCREENSHOT"
    CONFIRMATION_EMAIL = "CONFIRMATION_EMAIL"
    MANUAL_CONFIRMATION = "MANUAL_CONFIRMATION"
    VENDOR_CONFIRMATION = "VENDOR_CONFIRMATION"
    REGULATOR_CONFIRMATION = "REGULATOR_CONFIRMATION"


class PortalJobType(StrEnum):
    START_BROWSER_SESSION = "START_BROWSER_SESSION"
    NAVIGATE_PORTAL = "NAVIGATE_PORTAL"
    ENTER_FIELDS = "ENTER_FIELDS"
    UPLOAD_DOCUMENTS = "UPLOAD_DOCUMENTS"
    RUN_PORTAL_VALIDATION = "RUN_PORTAL_VALIDATION"
    CAPTURE_PRE_SUBMISSION = "CAPTURE_PRE_SUBMISSION"
    RECONCILE_SESSION = "RECONCILE_SESSION"
    CAPTURE_SUBMISSION_RESULT = "CAPTURE_SUBMISSION_RESULT"
    CLOSE_BROWSER_SESSION = "CLOSE_BROWSER_SESSION"


class PortalJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_HUMAN = "WAITING_HUMAN"
    COMPLETED = "COMPLETED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_REVIEW = "FAILED_REVIEW"
    CANCELLED = "CANCELLED"


class DiscrepancyCode(StrEnum):
    VALUE_MISMATCH = "VALUE_MISMATCH"
    FIELD_MISSING = "FIELD_MISSING"
    UNEXPECTED_PORTAL_VALUE = "UNEXPECTED_PORTAL_VALUE"
    DOCUMENT_MISSING = "DOCUMENT_MISSING"
    DOCUMENT_EXTRA = "DOCUMENT_EXTRA"
    DOCUMENT_VERSION_MISMATCH = "DOCUMENT_VERSION_MISMATCH"
    ENTITY_MISMATCH = "ENTITY_MISMATCH"
    FILING_TYPE_MISMATCH = "FILING_TYPE_MISMATCH"
    DATE_MISMATCH = "DATE_MISMATCH"
    PORTAL_VALIDATION_ERROR = "PORTAL_VALIDATION_ERROR"
    PORTAL_CHANGED = "PORTAL_CHANGED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


SENSITIVE_HANDOFF_TYPES = frozenset(
    {
        HandoffType.LOGIN.value,
        HandoffType.TERMS_ACCEPTANCE.value,
        HandoffType.MFA.value,
        HandoffType.CAPTCHA.value,
        HandoffType.ATTESTATION.value,
        HandoffType.SIGNATURE.value,
        HandoffType.PAYMENT.value,
        HandoffType.FINAL_SUBMIT.value,
    }
)
